markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: false
permalink: none
exclude: ["en-US/images/precompressed/", "node_modules", "Gruntfile.js", "package.json"]
url: http://nrsiward.github.io/fontdevbestpractices
baseurl: /fontdevbestpractices
repourl: //github.com/nrsiward/fontdevbestpractices
title: Font Development Best Practices
subtitle: A book about how to create great fonts
